//error
try {
  console.log(a);
} catch (err) {
  console.log("Something went wrong");
}